create table "user" (
	id bigint generated by default as identity,
	first_name varchar (40) not null,
	last_name varchar(40) not null,
	username varchar (50) not null,
	email varchar(70) not null,
	"password" varchar(20) not null,
	"user_role_id" bigint not null,
	foreign key ("user_role_id") references "user_role" (id),
	primary key (id)
);